### ISSUE TITLE
Merge to PF1 System(?)

### ISSUE THREAD

**Issue by HaydenReeve** [baileymh/pf1e-content#10]
Hi,

Quickly, I wanted to thank you for all the hard work you've put into this! From the pathfinder community, I wanted to thank you!

My question relates to the PF1 system; would it be appropriate to merge these updates and changes to the PF1 system itself, or is there a reason why that would not be a good idea (conflictions, etc.)

Thanks for any time taken to answer this question.

**Comment by baileymh** [comment]
Thanks! The appreciation and gratitude I've received means a lot to me. 

We've talked with the PF1 sys devs, and a majority of the items in this were created with the intention of them being adopted and incorporated into the system. 

However, the devs are working on some features that may change how things work, along with the incoming changes from Foundry 0.8.0, that make merging them now less than ideal. Additionally, since the feats and traits added in this module don't have appropriate changes, it might be best to wait until they are fully-features before merging. 

Eventually the plan is to merge them, but it will just take some time, as this is still usable and other features and bug fixes for the PF1 devs are a higher priority.
