### ISSUE TITLE
No valid manifest file in latest update

### ISSUE THREAD

**Issue by captchaoss** [baileymh/pf1e-content#13]
When I try to update in Foundry VTT it gives an error that the json "did not provide a valid manifest file." 

I don't know if this is the problem, but the difference I see looking at the version I have, which is 0.1.46 the manifest reads 
  "manifest": "https://github.com/baileymh/pf1e-content/releases/download/main/module.json",
In version 0.1.54 it reads
  "manifest": "https://raw.githubusercontent.com/baileymh/pf1e-content/main/module.json",

**Comment by baileymh** [comment]
Hi captchaoss, 

You will need to uninstall and reinstall the module through the module browser. 

I had made a mistake in the manifest link for version 0.1.46. As it says, the manifest link is invalid. Unfortunately, due to the way things work for foundry, there is no way for me to correct or update the link for people who are on that version, as there isn't a way for me to make that particular link valid. So it requires people to reinstall the module to get the new manifest link. 

Once you reinstall everything should work as expected (you won't lose anything). 
Apologies for the inconvenience!
